[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "httpx2-negotiate-sspi"
dynamic = ["version"]
description = "HTTPX Negotiate authentication using Windows SSPI."
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE.txt"]
authors = [
    { name = "achapkowski", email = "achapkowski@esri.com" },
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Win32 (MS Windows)",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "httpx2>=2.1.0,<3",
    "pywin32>=223; platform_system == 'Windows'",
]

[project.optional-dependencies]
dev = [
    "build",
    "coverage>=7",
]
doc = ["sphinx", "sphinx-rtd-theme"]

[project.urls]
Homepage = "https://github.com/achapkowski/httpx2_negotiate_sspi"
Documentation = "https://achapkowski.github.io/httpx2_negotiate_sspi"

[tool.setuptools.dynamic]
version = { attr = "httpx2_negotiate_sspi.__version__.__version__" }
